### ISSUE TITLE
Error loading discovery document: Issuer name is missing

### ISSUE THREAD

**Issue by vietxuan-nguyen** [IdentityModel/IdentityModel.OidcClient#344]
I'm using IdentityModel 5.1.0 and IdentityModel.OidcClient 4.0.0 for my library to support the OAuth2 Authentication Flow of MS Azure Active Directory.

This is my library code, this function will be returned the Authorize URL of Azure AD: 
 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
internal async Task<AuthorizeUrlResponse> GetAuthorizeUrl(string discoveryEndpoint, string clientId, string redirectUrl, string prompt)
        {
            var authState = await new OidcClient(
                new OidcClientOptions
                {
                    Authority = discoveryEndpoint,
                    ClientId = clientId,
                    RedirectUri = redirectUrl,
                    Scope = "openid profile email offline_access",
                    TokenClientCredentialStyle = ClientCredentialStyle.PostBody,
                    Policy = { Discovery = { ValidateEndpoints = false } }
                    }).PrepareLoginAsync().ConfigureAwait(false);

            return new AuthorizeUrlResponse
            {
                CodeVerifier = authState.CodeVerifier,
                AuthorizeUrl = $"{authState.StartUrl}&prompt={prompt}",
                State = authState.State
            };
        }

This function is worked as expected with the MVC web example. But if it is called from MVC web + ExtJS UI, it will be returned the exception: 

Timestamp: 12/21/2021 11:55:33 AM
Message: [.ctor]GetAuthorizeUrlAsync: System.InvalidOperationException: Error loading discovery document: Issuer name is missing
   at IdentityModel.OidcClient.OidcClient.<EnsureProviderInformationAsync>d__17.MoveNext() in /_/src/OidcClient/OidcClient.cs:line 395
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityModel.OidcClient.OidcClient.<EnsureConfigurationAsync>d__16.MoveNext() in /_/src/OidcClient/OidcClient.cs:line 373
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityModel.OidcClient.OidcClient.<PrepareLoginAsync>d__10.MoveNext() in /_/src/OidcClient/OidcClient.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AzureAD.Library.Auth.AuthorizationCode.<GetAuthorizeUrl>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityProviderLibrary.IdProviderLibrary.<GetAuthorizeUrlAsync>d__4.MoveNext()

If i set ValidateIssuerName = false of  OidcClientOptions.Policy  like that

var authState = await new OidcClient(
                new OidcClientOptions
                {
                    Authority = discoveryEndpoint,
                    ClientId = clientId,
                    RedirectUri = redirectUrl,
                    Scope = "openid profile email offline_access",
                    TokenClientCredentialStyle = ClientCredentialStyle.PostBody,
                    Policy = { Discovery = { ValidateEndpoints = false, ValidateIssuerName = false } }
                    }).PrepareLoginAsync().ConfigureAwait(false);

The other exception is returned

Timestamp: 12/21/2021 10:33:18 AM
Message: [.ctor]GetAuthorizeUrlAsync: System.InvalidOperationException: Error loading discovery document: Error connecting to https://login.microsoftonline.com/c69129ab-0f03-4787-847b-043d88ccd6b2/v2.0/.well-known/openid-configuration. Operation is not valid due to the current state of the object.. ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at System.Text.Json.JsonElement.EnumerateObject()
   at IdentityModel.Client.DiscoveryDocumentResponse.ValidateEndpoints(JsonElement json, DiscoveryPolicy policy) in D:\a\IdentityModel\IdentityModel\src\Client\Messages\DiscoveryDocumentResponse.cs:line 176
   at IdentityModel.Client.DiscoveryDocumentResponse.Validate(DiscoveryPolicy policy) in D:\a\IdentityModel\IdentityModel\src\Client\Messages\DiscoveryDocumentResponse.cs:line 115
   at IdentityModel.Client.DiscoveryDocumentResponse.InitializeAsync(Object initializationData) in D:\a\IdentityModel\IdentityModel\src\Client\Messages\DiscoveryDocumentResponse.cs:line 31
   at IdentityModel.Client.ProtocolResponse.<FromHttpResponseAsync>d__0`1.MoveNext() in D:\a\IdentityModel\IdentityModel\src\Client\Messages\ProtocolResponse.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityModel.Client.HttpClientDiscoveryExtensions.<GetDiscoveryDocumentAsync>d__1.MoveNext() in D:\a\IdentityModel\IdentityModel\src\Client\Extensions\HttpClientDiscoveryExtensions.cs:line 91
   --- End of inner exception stack trace ---
   at IdentityModel.OidcClient.OidcClient.<EnsureProviderInformationAsync>d__17.MoveNext() in /_/src/OidcClient/OidcClient.cs:line 407
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityModel.OidcClient.OidcClient.<EnsureConfigurationAsync>d__16.MoveNext() in /_/src/OidcClient/OidcClient.cs:line 373
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdentityModel.OidcClient.OidcClient.<PrepareLoginAsync>d__10.MoveNext() in /_/src/OidcClient/OidcClient.cs:line 112

Please give me your advice in this issue, how to can i resolve it. Many thanks for your advice

Thanks & Best regards

Nguyen Xuan Viet

**Comment by leastprivilege** [comment]
Well - apparently

> Error loading discovery document: Issuer name is missing

Issuer name is required per OIDC discovery spec.

**Comment by vietxuan-nguyen** [comment]
Yes, so if the "Policy = { Discovery = { ValidateEndpoints = false, ValidateIssuerName = false } }", this error occurs "Message: [.ctor]GetAuthorizeUrlAsync: System.InvalidOperationException: Error loading discovery document: Error connecting to https://login.microsoftonline.com/c69129ab-0f03-4787-847b-043d88ccd6b2/v2.0/.well-known/openid-configuration. Operation is not valid due to the current state of the object.. ---> System.InvalidOperationException: Operation is not valid due to the current state of the object."

**Comment by leastprivilege** [comment]
Sorry - I don't know. Never had this problem myself.

Maybe get the source code and debug it?

**Comment by vietxuan-nguyen** [comment]
Yes, i found my issue. Please help me to close this issue. Many thanks for your support

**Comment by leastprivilege** [comment]
..and what was it?

**Comment by vietxuan-nguyen** [comment]
i added these lines on web.config

`<dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
      </dependentAssembly>`

**Comment by leastprivilege** [comment]
OK...
